name: Build and Deploy to https://ydsh.pages.dev and https://yourdash.pages.dev

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [21.7.1]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11 # or "latest"

      - name: Install dependencies
        run: bun install

      - name: Build website
        run: (cd ./packages/web && bun run build)
#
#      - name: Deploy to external repository
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.SSH_DEPLOY_KEY }}
#
#        with:
#          source-directory: packages/web/dist/
#          destination-github-username: yourdash-app
#          destination-repository-name: ydsh-dev
#          user-email: ewsgit@duck.com
#          target-branch: "gh-pages"
