name: Build and Deploy to https://ydsh.pages.dev and https://yourdash.pages.dev

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.1]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: (cd ./main/web && yarn build)

      - name: Deploy to "yourdash.pages.dev" and "yourdash-app.github.io"
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: main/web/dist/
          destination-github-username: yourdash-app
          destination-repository-name: "yourdash-app.github.io"
          user-email: ewsgit@duck.com
          target-branch: main

      - name: Deploy to "ydsh.pages.dev" and "yourdash-app.github.io/yourdash"
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: main/web/dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
